# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('uid', models.CharField(max_length=300)),
                ('rid', models.CharField(max_length=300)),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('uid', models.CharField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('description', models.CharField(max_length=140)),
            ],
        ),
    ]
